//
//  ModelModels.swift
//  DigitalDevcasts
//
//  Created by Innovecto iOS on 4/23/16.
//  Copyright (c) 2016 Digital Devcasts. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct ModelRequest
{
}

struct ModelResponse
{
}

struct ModelViewModel
{
}
